name:                 blackjack
version:              0.1.0.0
visibility:           public
id:                   blackjack-0.1.0.0-inplace
key:                  blackjack-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           the.great.deceiver.hvedrung@gmail.com
author:               Loki
synopsis:             BlackJack
category:             Game
abi:                  inplace
exposed:              True
exposed-modules:      Cards Game IOFloor
import-dirs:
    /home/loki/work/haskell/blackjack/dist-newstyle/build/x86_64-linux/ghc-9.10.3/blackjack-0.1.0.0/build

library-dirs:
    /home/loki/work/haskell/blackjack/dist-newstyle/build/x86_64-linux/ghc-9.10.3/blackjack-0.1.0.0/build

library-dirs-static:
    /home/loki/work/haskell/blackjack/dist-newstyle/build/x86_64-linux/ghc-9.10.3/blackjack-0.1.0.0/build

dynamic-library-dirs:
    /home/loki/work/haskell/blackjack/dist-newstyle/build/x86_64-linux/ghc-9.10.3/blackjack-0.1.0.0/build

data-dir:             /home/loki/work/haskell/blackjack/.
hs-libraries:         HSblackjack-0.1.0.0-inplace
depends:
    base-4.20.2.0-127e bytestring-0.12.2.0-825f mtl-2.3.1-bcd6
    random-1.3.1-30e7a3c79f5feeb0d0e3b538b44bad5ec36f3ac7801869de67508646ed9bd3ed
    text-2.1.3-9f75

haddock-interfaces:
    /home/loki/work/haskell/blackjack/dist-newstyle/build/x86_64-linux/ghc-9.10.3/blackjack-0.1.0.0/doc/html/blackjack/blackjack.haddock

haddock-html:
    /home/loki/work/haskell/blackjack/dist-newstyle/build/x86_64-linux/ghc-9.10.3/blackjack-0.1.0.0/doc/html/blackjack
